version: '3.8'

services:
  db:
    image: mysql:8.0.2
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Sh0pPer_S3rvEr
      MYSQL_DATABASE: shopper_test
      MYSQL_USER: luiz
      MYSQL_PASSWORD: luiz098&
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: node_app
    environment:
      DATABASE_URL: mysql://luiz:luiz098&@db:3306/shopper_test
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      # - .:/usr/src/app
      - mysql_data:/var/lib/mysql
    command: >
      sh -c "
        npx prisma db push &&
        npm run start
      "

volumes:
  mysql_data:
